#!/usr/bin/env python3
"""
Připraví subset fontu DM Sans (Regular) pro Guardian – výstup C header s PROGMEM polem
pro OpenFontRender (TTF z paměti).

Použití:
  1. Nainstaluj fonttools: pip install fonttools
  2. Stáhni DM Sans z https://fonts.google.com/specimen/DM+Sans (Download family),
     rozbal a zkopíruj DMSans-Regular.ttf do tools/fonts/DMSans-Regular.ttf
     (nebo nech skript stáhnout – viz níže)
  3. Z kořene projektu: python3 tools/prepare_dmsans_font.py

Výstup: src/media/DMSans_subset.h (pole DMSans_Regular_subset[] PROGMEM).
V firmware pak při GUARDIAN načti tento font místo DigitalNumbers (viz docs/DM_SANS_FONT.md).
"""

import os
import sys
import struct

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(SCRIPT_DIR)
FONTS_DIR = os.path.join(SCRIPT_DIR, "fonts")
TTF_PATH = os.path.join(FONTS_DIR, "DMSans-Regular.ttf")
OUTPUT_HEADER = os.path.join(PROJECT_ROOT, "src", "media", "DMSans_subset.h")

# Znaky potřebné pro mining obrazovky: čísla, jednotky KH/s, popisky, čas
UNICODES_NEEDED = (
    "U+0020-007F"   # ASCII (mezera, číslice, písmena, : . / atd.)
    "U+00A0-00FF"   # Latin-1 (háčky, čárky pro případné texty)
)


def ensure_font_file():
    """Zajistí, že TTF je v tools/fonts/. Zkusí stáhnout z GitHubu."""
    if os.path.isfile(TTF_PATH):
        return True
    os.makedirs(FONTS_DIR, exist_ok=True)
    try:
        import urllib.request
        url = "https://github.com/google/fonts/raw/main/ofl/dmsans/DMSans-Regular.ttf"
        req = urllib.request.Request(url, headers={"User-Agent": "Guardian/1.0"})
        with urllib.request.urlopen(req, timeout=15) as r:
            with open(TTF_PATH, "wb") as f:
                f.write(r.read())
        print("Staženo:", TTF_PATH)
        return True
    except Exception as e:
        print("Stažení selhalo:", e, file=sys.stderr)
        print("Stáhni ručně: https://fonts.google.com/specimen/DM+Sans → Download → rozbal DMSans-Regular.ttf do", FONTS_DIR, file=sys.stderr)
        return False


def subset_ttf(input_path, output_path):
    """Vytvoří subset TTF (fonttools pyftsubset)."""
    import subprocess
    try:
        subprocess.run(
            [
                sys.executable,
                "-m",
                "fontTools.subset",
                input_path,
                f"--unicodes={UNICODES_NEEDED}",
                f"--output-file={output_path}",
                "--layout-features=*",
                "--name-IDs=*",
            ],
            check=True,
            capture_output=True,
        )
        return True
    except FileNotFoundError:
        print("Nainstaluj fonttools: pip install fonttools", file=sys.stderr)
        return False
    except subprocess.CalledProcessError as e:
        print("Subset selhal:", e.stderr.decode() if e.stderr else e, file=sys.stderr)
        return False


def ttf_to_c_header(ttf_path, out_header_path, array_name="DMSans_Regular_subset"):
    """Přečte TTF a zapíše ho jako C pole do .h souboru."""
    with open(ttf_path, "rb") as f:
        data = f.read()
    size = len(data)
    lines = []
    lines.append("// DM Sans Regular (subset) for Guardian – generated by tools/prepare_dmsans_font.py")
    lines.append("// Do not edit by hand. Re-run the script to regenerate.")
    lines.append("")
    lines.append("#ifndef DM_SANS_SUBSET_H")
    lines.append("#define DM_SANS_SUBSET_H")
    lines.append("")
    lines.append(f"const unsigned char {array_name}[] PROGMEM = {{")
    for i in range(0, size, 16):
        chunk = data[i : i + 16]
        hex_str = ", ".join(f"0x{b:02X}" for b in chunk)
        lines.append(f"  {hex_str},")
    lines.append("};")
    lines.append("")
    lines.append(f"#define {array_name}_SIZE {size}")
    lines.append("#endif")
    os.makedirs(os.path.dirname(out_header_path), exist_ok=True)
    with open(out_header_path, "w") as f:
        f.write("\n".join(lines))
    print("Zapsáno:", out_header_path, f"({size} bajtů)")
    return True


def main():
    if not ensure_font_file():
        return 1
    subset_path = TTF_PATH + ".subset.ttf"
    if subset_ttf(TTF_PATH, subset_path):
        ttf_to_c_header(subset_path, OUTPUT_HEADER)
        try:
            os.remove(subset_path)
        except OSError:
            pass
    else:
        # Bez subsetu – celý font (větší, ale funguje)
        print("Používám celý TTF (bez subsetu). Pro menší velikost nainstaluj fonttools.", file=sys.stderr)
        ttf_to_c_header(TTF_PATH, OUTPUT_HEADER)
    return 0


if __name__ == "__main__":
    sys.exit(main())
