#!/usr/bin/env python3
"""
Build a DM Sans (Regular) subset for Guardian. Writes a C header with a PROGMEM
array for OpenFontRender (TTF kept in memory).

Usage:
  1. Install fonttools: pip install fonttools
  2. Download DM Sans from https://fonts.google.com/specimen/DM+Sans (Download family),
     unzip it, and copy DMSans-Regular.ttf to tools/fonts/DMSans-Regular.ttf
     (or let the script download it, see below)
  3. From the project root: python3 tools/prepare_dmsans_font.py

Output: src/media/DMSans_subset.h (array DMSans_Regular_subset[] PROGMEM).
A GUARDIAN build loads this font. See docs/DM_SANS_FONT.md.
"""

import os
import sys
import struct

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(SCRIPT_DIR)
FONTS_DIR = os.path.join(SCRIPT_DIR, "fonts")
TTF_PATH = os.path.join(FONTS_DIR, "DMSans-Regular.ttf")
OUTPUT_HEADER = os.path.join(PROJECT_ROOT, "src", "media", "DMSans_subset.h")

# Glyphs used on the mining screens: digits, KH/s units, labels, time
UNICODES_NEEDED = (
    "U+0020-007F"   # ASCII (space, digits, letters, : . / and so on)
    "U+00A0-00FF"   # Latin-1 (accents, if a label needs them)
)


def ensure_font_file():
    """Make sure the TTF is in tools/fonts/. Tries a GitHub download."""
    if os.path.isfile(TTF_PATH):
        return True
    os.makedirs(FONTS_DIR, exist_ok=True)
    try:
        import urllib.request
        url = "https://github.com/google/fonts/raw/main/ofl/dmsans/DMSans-Regular.ttf"
        req = urllib.request.Request(url, headers={"User-Agent": "Guardian/1.0"})
        with urllib.request.urlopen(req, timeout=15) as r:
            with open(TTF_PATH, "wb") as f:
                f.write(r.read())
        print("Downloaded:", TTF_PATH)
        return True
    except Exception as e:
        print("Download failed:", e, file=sys.stderr)
        print("Download it by hand: https://fonts.google.com/specimen/DM+Sans -> Download -> unzip DMSans-Regular.ttf into", FONTS_DIR, file=sys.stderr)
        return False


def subset_ttf(input_path, output_path):
    """Write a subset TTF (fonttools pyftsubset)."""
    import subprocess
    try:
        subprocess.run(
            [
                sys.executable,
                "-m",
                "fontTools.subset",
                input_path,
                f"--unicodes={UNICODES_NEEDED}",
                f"--output-file={output_path}",
                "--layout-features=*",
                "--name-IDs=*",
            ],
            check=True,
            capture_output=True,
        )
        return True
    except FileNotFoundError:
        print("Install fonttools: pip install fonttools", file=sys.stderr)
        return False
    except subprocess.CalledProcessError as e:
        print("Subset failed:", e.stderr.decode() if e.stderr else e, file=sys.stderr)
        return False


def ttf_to_c_header(ttf_path, out_header_path, array_name="DMSans_Regular_subset"):
    """Read a TTF and write it as a C array in a .h file."""
    with open(ttf_path, "rb") as f:
        data = f.read()
    size = len(data)
    lines = []
    lines.append("// DM Sans Regular (subset) for Guardian, generated by tools/prepare_dmsans_font.py")
    lines.append("// Do not edit by hand. Re-run the script to regenerate.")
    lines.append("")
    lines.append("#ifndef DM_SANS_SUBSET_H")
    lines.append("#define DM_SANS_SUBSET_H")
    lines.append("")
    lines.append(f"const unsigned char {array_name}[] PROGMEM = {{")
    for i in range(0, size, 16):
        chunk = data[i : i + 16]
        hex_str = ", ".join(f"0x{b:02X}" for b in chunk)
        lines.append(f"  {hex_str},")
    lines.append("};")
    lines.append("")
    lines.append(f"#define {array_name}_SIZE {size}")
    lines.append("#endif")
    os.makedirs(os.path.dirname(out_header_path), exist_ok=True)
    with open(out_header_path, "w") as f:
        f.write("\n".join(lines))
    print("Wrote:", out_header_path, f"({size} bytes)")
    return True


def main():
    if not ensure_font_file():
        return 1
    subset_path = TTF_PATH + ".subset.ttf"
    if subset_ttf(TTF_PATH, subset_path):
        ttf_to_c_header(subset_path, OUTPUT_HEADER)
        try:
            os.remove(subset_path)
        except OSError:
            pass
    else:
        # No subset: the whole font (larger, but it works)
        print("Using the full TTF (no subset). Install fonttools for a smaller file.", file=sys.stderr)
        ttf_to_c_header(TTF_PATH, OUTPUT_HEADER)
    return 0


if __name__ == "__main__":
    sys.exit(main())
