#!/usr/bin/env python3
"""
Build DM Sans Regular and Bold subsets for Guardian. Writes a C header with
PROGMEM arrays for OpenFontRender (TTF kept in memory).

Usage:
  1. Install fonttools: pip install fonttools
  2. Download DM Sans from https://fonts.google.com/specimen/DM+Sans (Download family),
     unzip it, and copy DMSans-Regular.ttf to tools/fonts/DMSans-Regular.ttf
     (or let the script download it, see below). Bold is read from
     fonts/static/DMSans-Bold.ttf.
  3. From the project root: python3 tools/prepare_dmsans_font.py

Output: src/media/DMSans_subset.h
  DMSans_Regular_subset[] and DMSans_Bold_subset[].
A GUARDIAN build loads both. See docs/DM_SANS_FONT.md.
"""

import os
import sys
import struct

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(SCRIPT_DIR)
FONTS_DIR = os.path.join(SCRIPT_DIR, "fonts")
TTF_PATH = os.path.join(FONTS_DIR, "DMSans-Regular.ttf")
BOLD_PATH = os.path.join(PROJECT_ROOT, "fonts", "static", "DMSans-Bold.ttf")
OUTPUT_HEADER = os.path.join(PROJECT_ROOT, "src", "media", "DMSans_subset.h")

# Glyphs used on the mining screens: digits, KH/s units, labels, time
UNICODES_NEEDED = (
    "U+0020-007F"   # ASCII (space, digits, letters, : . / and so on)
    "U+00A0-00FF"   # Latin-1 (accents, if a label needs them)
)


def ensure_font_file():
    """Make sure the TTF is in tools/fonts/. Tries a GitHub download."""
    if os.path.isfile(TTF_PATH):
        return True
    os.makedirs(FONTS_DIR, exist_ok=True)
    try:
        import urllib.request
        url = "https://github.com/google/fonts/raw/main/ofl/dmsans/DMSans-Regular.ttf"
        req = urllib.request.Request(url, headers={"User-Agent": "Guardian/1.0"})
        with urllib.request.urlopen(req, timeout=15) as r:
            with open(TTF_PATH, "wb") as f:
                f.write(r.read())
        print("Downloaded:", TTF_PATH)
        return True
    except Exception as e:
        print("Download failed:", e, file=sys.stderr)
        print("Download it by hand: https://fonts.google.com/specimen/DM+Sans -> Download -> unzip DMSans-Regular.ttf into", FONTS_DIR, file=sys.stderr)
        return False


def subset_ttf(input_path, output_path):
    """Write a subset TTF (fonttools pyftsubset)."""
    import subprocess
    try:
        subprocess.run(
            [
                sys.executable,
                "-m",
                "fontTools.subset",
                input_path,
                f"--unicodes={UNICODES_NEEDED}",
                f"--output-file={output_path}",
                "--layout-features=*",
                "--name-IDs=*",
            ],
            check=True,
            capture_output=True,
        )
        return True
    except FileNotFoundError:
        print("Install fonttools: pip install fonttools", file=sys.stderr)
        return False
    except subprocess.CalledProcessError as e:
        print("Subset failed:", e.stderr.decode() if e.stderr else e, file=sys.stderr)
        return False


def array_lines(ttf_path, array_name):
    """C array lines for one TTF. Returns (lines, size)."""
    with open(ttf_path, "rb") as f:
        data = f.read()
    lines = [f"const unsigned char {array_name}[] PROGMEM = {{"]
    for i in range(0, len(data), 16):
        chunk = data[i : i + 16]
        lines.append("  " + ", ".join(f"0x{b:02X}" for b in chunk) + ",")
    lines.append("};")
    lines.append("")
    lines.append(f"#define {array_name}_SIZE {len(data)}")
    lines.append("")
    return lines, len(data)


def write_header(faces, out_header_path):
    """faces: list of (ttf_path, array_name)."""
    lines = [
        "// DM Sans Regular and Bold (subset) for Guardian, generated by tools/prepare_dmsans_font.py",
        "// Do not edit by hand. Re-run the script to regenerate.",
        "",
        "#ifndef DM_SANS_SUBSET_H",
        "#define DM_SANS_SUBSET_H",
        "",
    ]
    sizes = []
    for ttf_path, array_name in faces:
        face_lines, size = array_lines(ttf_path, array_name)
        lines.extend(face_lines)
        sizes.append(size)
    lines.append("#endif")
    os.makedirs(os.path.dirname(out_header_path), exist_ok=True)
    with open(out_header_path, "w") as f:
        f.write("\n".join(lines) + "\n")
    print("Wrote:", out_header_path, "(" + ", ".join(str(s) for s in sizes) + " bytes)")


def subset_or_full(src_path):
    """Return a path to a subset TTF, or the original if subsetting fails."""
    subset_path = src_path + ".subset.ttf"
    if subset_ttf(src_path, subset_path):
        return subset_path, True
    print("Using the full TTF (no subset):", src_path, file=sys.stderr)
    return src_path, False


def main():
    if not ensure_font_file():
        return 1
    if not os.path.isfile(BOLD_PATH):
        print("Missing bold font:", BOLD_PATH, file=sys.stderr)
        return 1
    faces = []
    temps = []
    for src, name in ((TTF_PATH, "DMSans_Regular_subset"), (BOLD_PATH, "DMSans_Bold_subset")):
        path, is_temp = subset_or_full(src)
        faces.append((path, name))
        if is_temp:
            temps.append(path)
    write_header(faces, OUTPUT_HEADER)
    for path in temps:
        try:
            os.remove(path)
        except OSError:
            pass
    return 0


if __name__ == "__main__":
    sys.exit(main())
